/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-02-02 03:20:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Access Management System</title>\r\n");
      out.write("<!-- Core CSS - Include with every page -->\r\n");
      out.write("<link href=\"assets/plugins/bootstrap/bootstrap.css\" rel=\"stylesheet\" />\t\r\n");
      out.write("<link href=\"assets/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background:url('img/backimg.jpg') no-repeat;\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<nav class=\"navbar navbar-inverse navbar-fixed-top\" style=\"background:#ffffff;border:none;\">\r\n");
      out.write("  \r\n");
      out.write("  <div> \r\n");
      out.write("   <div align='center'  style=\"color:#FFFFFF;\"><br>\r\n");
      out.write("    <h1 style=\"color:#008000\">Access Management System</h1></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br /> \t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-4 col-md-offset-4\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\"  id=\"divErr\" style=\"margin-top:100px;\">\r\n");
      out.write("              \t\t<input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${err}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"txtErr\">\r\n");
      out.write("                    \r\n");
      out.write("                        <div class=\"panel-heading\">\r\n");
      out.write("                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t<div class=\"login-panel panel panel-default\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\"><b>Please Sign In</b></h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<form name='login' id=\"logina\" method='post'\r\n");
      out.write("\t\t\t\t\t\t\taction='j_spring_security_check'>\r\n");
      out.write("\t\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"form-control\" placeholder=\"Username\" id=\"user\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname='j_username' type=\"text\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input class=\"form-control\" placeholder=\"Password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname='j_password' type=\"password\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Change this to a button or input when using this as a form -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type='submit' id=\"clickme\"  class='btn btn-lg btn-success ladda-button'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  data-style=\"expand-right\" ><span class=\"ladda-label\"><b>Login</b></span></button>\r\n");
      out.write("\t\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div><br><br><br><br/><br/>\r\n");
      out.write("\t<div class=\"footer\"><div align=\"center\"  style=\"color:#0C0E75;\"class=\"container\"><B>Designed and Developed By:<br/> IT DEPARTMENT <br/>SANIMA BANK PVT. LTD</B></div></div>\r\n");
      out.write("\t<!-- Core Scripts - Include with every page -->\r\n");
      out.write("\t<script src=\"assets/plugins/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t<script src=\"assets/plugins/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write(" \r\n");
      out.write(" <script>\r\n");
      out.write("  \r\n");
      out.write("\t\t$(document)\r\n");
      out.write("\t\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tinit();\r\n");
      out.write("\t\t\t\t\t\t\tif (msieversion()) {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"Browser Not Supported. Please use 'Googl Chrome' instead. Download Google Chrome from the link\");\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.location.href = \"https://www.google.com/intl/en/chrome/browser/\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction msieversion() {\r\n");
      out.write("\t\t\tvar ua = window.navigator.userAgent;\r\n");
      out.write("\t\t\tvar msie = ua.indexOf(\"MSIE \");\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (msie > 0) // If Internet Explorer, return version number\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction init() {\r\n");
      out.write("\t\t\tvar e = $(\"#txtErr\").val();\r\n");
      out.write("\t\t\tif (e != null && e != \"1\")\r\n");
      out.write("\t\t\t\t$('#divErr').hide();\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t$('#divErr').show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#clickme\").click(function(e){\r\n");
      out.write("\t\t\t$(\".ladda-label\").html(\"Authenticating.....\");\r\n");
      out.write("\t\t\tvar l = Ladda.create(this);\r\n");
      out.write("\t\t \tl.start();\r\n");
      out.write("\t\t \t$(\"#logina\").submit();\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t \t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
